site_name: Wizor • SGSI
theme:
  name: material
nav:
  - Inicio: index.md
  - SGSI:
    - Alcance: sgsi/alcance.md
    - Roles: sgsi/roles.md
    - Metodología: sgsi/metodologia.md
  - Anexos:
    - Anexo A: anexos/anexo_a_politica.md
    - Anexo B: anexos/anexo_b_gestion_riesgos.md
    - Anexo C: anexos/anexo_c_integracion_solucion.md
    - Anexo D: anexos/anexo_d_responsabilidad_compartida.md
    - Anexo E: anexos/anexo_e_gestion_riesgos.md
  - Cambios: changelog/index.md
  - Evidencias: evidencias/solicitar_evidencias.md
